### ISSUE TITLE
failed when trying to include a new system

### ISSUE THREAD

**Issue by alexandergz1983** [padlocbio/padloc#11]
the warning is as follows: (18:53:16) WARNING >> hmm_meta.tsv - Missing values (<NA>) in required columns - ET (e.value.threshold), HC (hmm.coverage.threshold), TC (target.coverage.threshold) - see below

padloc --fna GCF_902849975.1_HP-ISR-7_genomic.fna --force --data /miniconda3/envs/padloc/padloc-db/ --debug --raw-out
(18:53:13) DEBUG  >>  $FAA_FILE: 
(18:53:13) DEBUG  >>  $FNA_FILE: /test/GCF_902849975.1_HP-ISR-7_genomic.fna
(18:53:13) DEBUG  >>  $GFF_FILE: 
(18:53:13) DEBUG  >>  $HMM_DATABASE: /miniconda3/envs/padloc/padloc-db//hmm/padlocdb.hmm
(18:53:13) DEBUG  >>  $YAML_DIR:/miniconda3/envs/padloc/padloc-db//sys/
(18:53:13) DEBUG  >>  $HMM_META: /miniconda3/envs/padloc/padloc-db//hmm_meta.txt
(18:53:13) DEBUG  >>  $SYS_META: /miniconda3/envs/padloc/padloc-db//sys_meta.txt
(18:53:13) DEBUG  >>  $OUT_DIR: .
(18:53:13) DEBUG  >>  $CPU: 1
(18:53:13) >> Predicting protein-coding genes with prodigal
(18:53:13) DEBUG  >>  prodigal -i /test/GCF_902849975.1_HP-ISR-7_genomic.fna -f gff -o ./GCF_902849975.1_HP-ISR-7_genomic_prodigal.gff -a ./GCF_902849975.1_HP-ISR-7_genomic_prodigal.faa -q
(18:53:15) DEBUG  >>  Finished @ mar nov  2 18:53:15 CET 2021 ... SUCCESSFUL
(18:53:15) >> Scanning GCF_902849975.1_HP-ISR-7_genomic for defence system proteins
(18:53:15) DEBUG  >>  hmmsearch --cpu 1 --acc --noali --domtblout ./GCF_902849975.1_HP-ISR-7_genomic.domtblout /miniconda3/envs/padloc/padloc-db//hmm/padlocdb.hmm ./GCF_902849975.1_HP-ISR-7_genomic_prodigal.faa
(18:53:15) DEBUG  >>  Finished @ mar nov  2 18:53:15 CET 2021 ... SUCCESSFUL
(18:53:15) >> Searching GCF_902849975.1_HP-ISR-7_genomic for defence systems
(18:53:15) DEBUG  >>  Rscript //miniconda3/envs/padloc/bin/bin/padloc.R -d ./GCF_902849975.1_HP-ISR-7_genomic.domtblout -f ./GCF_902849975.1_HP-ISR-7_genomic_prodigal.gff -h /miniconda3/envs/padloc/padloc-db//hmm_meta.txt -s /miniconda3/envs/padloc/padloc-db//sys_meta.txt -y /miniconda3/envs/padloc/padloc-db//sys/ -o . -b 1 -q 0 -p 1(18:53:16) DEBUG >> Start time: 2021-11-02 18:53:16
(18:53:16) DEBUG >> Reading hmm_meta.txt
(18:53:16) WARNING >> hmm_meta.tsv - Missing values (<NA>) in required columns - ET (e.value.threshold), HC (hmm.coverage.threshold), TC (target.coverage.threshold) - see below

    hmm.acc      hmm.name hmm.description protein.name
1 PDLC02225 PglZ_bacteria     phosphatase         PglZ
2 PDLC02227 BrxC_bacteria          ATPase         BrxC
  system.definition.shortcut   author number.seq length.hmm e.value.threshold
1                       <NA> Payne LJ         NA         NA             1e-05
2                       <NA> Payne LJ         NA         NA             1e-05
  hmm.coverage.threshold target.coverage.threshold system literature.ref
1                     NA                        NA   BREX      10/ggqhzm
2                     NA                        NA   BREX      10/ggqhzm
  database.ref comments
1         <NA>     <NA>
2         <NA>     <NA>

(18:53:16) WARNING >> hmm_meta.tsv - Filling with defaults (1E-05, 0.3, 0.3)
Warning message:
One or more parsing issues, see `problems()` for details 
(18:53:16) DEBUG >> Reading sys_meta.txt
(18:53:16) DEBUG >> Reading GCF_902849975.1_HP-ISR-7_genomic.domtblout
(18:53:16) DEBUG >> Reading GCF_902849975.1_HP-ISR-7_genomic_prodigal.gff
(18:53:17) DEBUG >> Merging domain, alias, and feature tables
(18:53:17) DEBUG >> Searching for defence systems
(18:53:17) >> Nothing found for GCF_902849975.1_HP-ISR-7_genomic
(18:53:17) DEBUG >> End time: 2021-11-02 18:53:17
(18:53:17) DEBUG >> Run time: 1.26394128799438

**Comment by leightonpayne** [comment]
Hi Alexander, would you mind attaching your edited `hmm_meta.txt` file here or <a href="mailto:leighton.payne@postgrad.otago.ac.nz?subject=[padlocbio/padloc] failed when trying to include a new system (Issue #11)">email it to me</a> so I could have a closer look? Thanks!

**Comment by alexandergz1983** [comment]
> Hi Alexander, would you mind attaching your edited `hmm_meta.txt` file here or [email it to me](mailto:leighton.payne@postgrad.otago.ac.nz?subject=[padlocbio/padloc] failed when trying to include a new system (Issue #11)) so I could have a closer look? Thanks!

hmm.accession	hmm.name	hmm.description	protein.name	secondary.name	author	hmm.nseq	hmm.length	e.val.threshold	hmm.coverage.threshold	target.coverage.threshold	system	literature.ref	database.ref	comment
PDLC02225	PglZ_bacteria	phosphatase	PglZ		Goldfard T			1E-05	0,3	0,3	BREX	10/ggqhzm		NA
PDLC02227	BrxC_bacteria	ATPase	BrxC		Goldfard T			1E-05	0,3	0,3	BREX	10/ggqhzm		NA

Hi, this is the test file hmm_meta.txt

**Comment by leightonpayne** [comment]
Cheers!

I believe the warning is due to the use of commas (`,`) to represent decimals in the thresholds. Decimals need to be expressed using periods (`.`) rather than commas (i.e. `0.3` instead of `0,3`). I've attached an `hmm_meta.txt` file that should work in your case.

We hope to be adding BREX systems in the near future so keep an eye out if you're interested.

Use this: [hmm_meta.txt](https://github.com/padlocbio/padloc/files/7466356/hmm_meta.txt)

**Comment by alexandergz1983** [comment]
> Cheers!
> 
> I believe the warning is due to the use of commas (`,`) to represent decimals in the thresholds. Decimals need to be expressed using periods (`.`) rather than commas (i.e. `0.3` instead of `0,3`). I've attached an `hmm_meta.txt` file that should work in your case.
> 
> We hope to be adding BREX systems in the near future so keep an eye out if you're interested.
> 
> Use this: [hmm_meta.txt](https://github.com/padlocbio/padloc/files/7466356/hmm_meta.txt)

Thank you.
