### ISSUE TITLE
Add option to fix Prodigal-generated GFF for externally generated GFF files

### ISSUE THREAD

**Issue by apcamargo** [padlocbio/padloc#13]
I'm executing PADLOC in a large dataset, so I ended up using a [wrapper](https://github.com/apcamargo/parallel-prodigal) to speed up Prodigal execution prior to calling PADLOC. Because PADLOC doesn't fix the records of externally supplied GFF files, I got the following error message:

```
(11:46:20 AM) WARNING >> 23 protein sequence IDs are missing from GFF file. Terminating.
```

To fix this I forced my PADLOC installation to fix the records files for external GFF files. Maybe it could be useful to provide an `--fix-prodigal-input` to make it easier for users to provide Prodigal inputs that were generated independently. This could be useful for users that need to run prodigal with alternative genetic codes or use wrappers to parallelize Prodigal.

**Comment by leightonpayne** [comment]
Hi Antônio, 

Good idea, I've added an option to force the GFF to be treated as if it were generated by prodigal internally, which should sort your issue.

```
--fix-prodigal    Set this flag when providing an FAA and GFF file 
                  generated with prodigal to force fixing of sequence IDs
```
