### ISSUE TITLE
could not find function "cur_group_id"

### ISSUE THREAD

**Issue by keaimajia** [padlocbio/padloc#17]
Hi, I got this error when running PADLOC. I have no idea how to fix this. Could you please help me with this? Thanks!

```
>> Searching GCF_009741465.1 for defence systems
Error in cur_group_id() : could not find function "cur_group_id"
Calls: format_output ... <Anonymous> -> mutate -> mutate.tbl_df -> mutate_impl
Execution halted
ERROR >> errexit on line 387
```

**Comment by JacksonLab** [comment]
Hello,

Please check all the required R dependencies are up-to-date. cur_group_id was added in dplyr 1.0

Cheers,

Simon
