### ISSUE TITLE
Question on `--crispr `

### ISSUE THREAD

**Issue by jiarong** [padlocbio/padloc#21]
What differences does `--crispr ` make in the output files? (`_padloc.csv` or `_padloc.gff`) Thanks!

**Comment by leightonpayne** [comment]
The `--crispr` option allows you to give PADLOC a CRISPRDetect output file (if run previously on the same genome) for inclusion of CRISPR arrays in the PADLOC output file. CRISPRDetect can also be run and handled automatically when using the [PADLOC webserver](https://padloc.otago.ac.nz/padloc/)
