### ISSUE TITLE
Solitary genes

### ISSUE THREAD

**Issue by Liqueurdefehling** [padlocbio/padloc#22]
Hi,

Does an option exist to show not only complete systems, but also solitary genes such as solitary methyltransferases ?
In other words, can we have access to the full landscape of defense genes, even if they are not included in complete systems?

Best,
Auriane

**Comment by leightonpayne** [comment]
No option exists currently, other than inspecting the raw output of HMMER (*.domtblout), although this will give you all the hits pre-e-value filtering. We could add a feature for returning all solitary genes, but our e-value cutoffs have not been optimised for this purpose - and the results would likely require further post-filtering.

I'll re-open this issue if this ever get added.
