### ISSUE TITLE
DMS_other

### ISSUE THREAD

**Issue by icemduru** [padlocbio/padloc#24]
Hi,

Very great tool. Could you tell me what is DMS_other, which appears in the results as a system. I could not find it on the "Defence systems included in PADLOC" page.

Regards
Cem

**Comment by StefaanVerwimp** [comment]
Hello,

The DMS_other system is defined [here](https://github.com/padlocbio/padloc-db/blob/master/sys/DMS_other.yaml). The [padloc-db github](https://github.com/padlocbio/padloc-db) page contains this kind of file for every defense system padloc is able to annotate.
All "sys_other" systems are potential systems, or some defense system gene homologs found close to each other in the genome. Thus these requires manual inspection and verification.

Hope that helped

**Comment by icemduru** [comment]
Thanks !
