### ISSUE TITLE
Bit score in output .csv file

### ISSUE THREAD

**Issue by scubalaina** [padlocbio/padloc#27]
Hi there!
This is not a technical issue (maybe I should have wrote this in an email?), but I was wondering why the bit score is not reported in the ".csv" output? Maybe this was mentioned in the manuscript or can be reported with a given flag, but I can't find it. I only see E values. Since bit score is calculated independent of a database (unlike E values), it would be really helpful to report that as well for us users who are annotating genomes/proteins across multiple databases. I am writing a python script to pull the bitscore from the .domtblout file - but just thought to suggest this potentially for future releases!
Thanks :)

**Comment by leightonpayne** [comment]
Hi Alaina, 

There's no particular reason that we don't include bit score in the output, and it would be easy to do, I'll add this suggestion to the list of things I'd like to implement in the near future when I find some time!

Cheers.

**Comment by scubalaina** [comment]
Great thanks!
Also - I might have missed this, but should we be using the CRISPR-Cas Class designations from [Koonin et al 2017](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5776717/) - which puts Types I, III and IV exclusive to Class 1 and Type II, V, and VI exclusive to Class 2? They type number is included in the name on Padloc but not the class (screenshot below). Just wanted to make sure I was using the right class designation - should I be going with the Koonin groupings? Thanks for the help! :)  
![Screenshot 2023-04-07 at 1 54 05 PM](https://user-images.githubusercontent.com/23300761/230654885-b95649b7-6ba7-42ce-bbbb-7ce971a5225c.png)

**Comment by leightonpayne** [comment]
We used [Makarova, K. S. et al. Evolutionary classification of CRISPR–Cas systems: a burst of class 2 and derived variants. Nat Rev Microbiol 18, 67–83 (2020)](https://doi.org/10.1038/s41579-019-0299-x) to guide our classification of CRISPR-Cas systems, I'd recommend referring to this article for class designations (the classes designated there are equivalent to Koonin, et al. 2017, but with updated type classifications).

**Comment by scubalaina** [comment]
Ah I see! Great thank you! :)
