### ISSUE TITLE
error: In library (tidyverse): there is no package called 'tidyverse'

### ISSUE THREAD

**Issue by Chiless** [padlocbio/padloc#29]
![image](https://user-images.githubusercontent.com/30303733/234654415-1cd9e74e-38af-4ae4-a1a2-7520e456fb25.png)

Dear all,

I am writing to you to report an error that I encountered while using the program. Despite having all the appropriate dependencies correctly installed with the correct versions, the program still generates an error when it tries to generate the files with the search results.

It seems that the program is performing the appropriate searches, but I need help with this error. Could someone please provide me with guidance on how to solve this?

Thank you very much.

**Comment by xinleee** [comment]
Finally found it from google:https://github.com/tidyverse/haven/issues/363
For people who googled to here, you may try this:
withr::with_makevars(c(PKG_LIBS = "-liconv"), install.packages("haven"), assignment = "+=")
It seems someone create a typo in somewhere.

**Comment by leightonpayne** [comment]
Hi @Chiless, if you installed `padloc` via `conda`, `tidyverse` should be installed alongside it. I would recommend installing (or reinstalling) with `conda` to fix this issue:

```bash
conda create -n padloc -c conda-forge -c bioconda -c padlocbio padloc
```

**Comment by leightonpayne** [comment]
See #28
