### ISSUE TITLE
Additional information regarding systems (what is "DSM_other" ?)

### ISSUE THREAD

**Issue by UriNeri** [padlocbio/padloc#32]
It would be great if in addition to prediction of a system there would be a column/value linking to a publication or info source explaining the system.  
If this information exists somewhere, it would be great to know where it is, as I'm a bit clueless as to what DMS_other and argonaute_solo mean.   
 Ideally, this information could be added to https://github.com/padlocbio/padloc-db/blob/master/sys_meta.txt

**Comment by leightonpayne** [comment]
Hi @UriNeri,

The proteins contributing to each model can be identified by inspecting the models (e.g. [DMS_other.yaml](https://github.com/padlocbio/padloc-db/blob/master/sys/DMS_other.yaml))

In the case of [`DMS_other`](https://github.com/padlocbio/padloc-db/blob/master/sys/DMS_other.yaml), this just stands for 'other DNA modification system', and is a very loose model capturing any co-localised proteins from various DNA modification–based systems (e.g. RM, BREX, DISARM, etc.), in an attempt to capture any weird or potentially new types of DNA modification–based systems. 

The [`argonaute_solo`](https://github.com/padlocbio/padloc-db/blob/master/sys/argonaute_solo.yaml) model captures prokaryotic Argonaute proteins that are not identified adjacent to any known pAgo-associated proteins.

Publications relevant to each system can be found on our [web server](https://padloc.otago.ac.nz/padloc/systeminformation/). I'll look into adding this info (and other notes) to the system metadata table as well for those not using the web server.

Cheers.

**Comment by leightonpayne** [comment]
System description and reference information added in padlocbio/padloc-db@2744fabbe3e66d3e47e08b0bcd4c4d6bc2ebccf1
