### ISSUE TITLE
Merge padloc.csv files for many genomes

### ISSUE THREAD

**Issue by AhmedElsherbini** [padlocbio/padloc#33]
Hello,

Thanks for developing this nice tool. Just as I usually work with many genomes and I usually like to look at distributions of systems in my genome and also having a presence /absence matrix for heatmaps, I developed this simple [script](https://github.com/AhmedElsherbini/PADLOC_stats) to aid me in this work. And I hope it can help any collogue with similar needs. If you have any suggestion for this, it is welcome.

**Comment by leightonpayne** [comment]
Hi @AhmedElsherbini, thanks for sharing!
