### ISSUE TITLE
Older `conda` versions install `padloc v1.1.0` rather than `padloc v2.0.0`

### ISSUE THREAD

**Issue by leightonpayne** [padlocbio/padloc#35]
For some reason, older versions of `conda` (possibly related to use of the older `pycosat` dependency solver) install `padloc v1.1.0` rather than `padloc v2.0.0` by default.

> [!IMPORTANT]
> To avoid this issue, you can specify `padloc v2.0.0` during installation (this should work regardless of `conda` version)
> ```bash
> create -n padloc -c conda-forge -c bioconda -c padlocbio padloc=2.0.0
> ```

> [!NOTE]
> To avoid future issues, you may also wish to:
> 1. Make sure your `conda` installation is up-to-date
> ```bash
> conda install -n base -c defaults 'conda>=23.9.0'
> ```
> 2. Make sure the new `libmamba` solver is available and active
> ```bash
> conda install -n base conda-libmamba-solver --solver=classic
> conda config --set solver libmamba
> ```

**Comment by NK181092** [comment]
Trying to install Padloc but the padloc database update command is not working
