### ISSUE TITLE
The output is missing

### ISSUE THREAD

**Issue by dabaoniu** [padlocbio/padloc#36]
Hi! I was trying to run padloc with

`padloc --fna GCF_004358345.1.fna --outdir output_padloc --cpu 2`

Then I get three output files: GCF_004358345.1.domtblout, GCF_004358345.1_prodigal.faa, and GCF_004358345.1_prodigal.gff. However, the two files _padloc.csv and _padloc.gff were not obtained, and I also got the warning:
```
Warning message:
One or more parsing issues, call `problems()` on your data frame for details,
e.g.:
  dat <- vroom(...)
  problems(dat) 
Warning message:
One or more parsing issues, call `problems()` on your data frame for details,
e.g.:
  dat <- vroom(...)
  problems(dat) 
Warning message:
In left_join(., hmm_meta, by = "hmm.name") :
  Detected an unexpected many-to-many relationship between `x` and `y`.
ℹ Row 11 of `x` matches multiple rows in `y`.
ℹ Row 1171 of `y` matches multiple rows in `x`.
ℹ If a many-to-many relationship is expected, set `relationship =
  "many-to-many"` to silence this warning.
```

I'd be really grateful for any insight!

**Comment by leightonpayne** [comment]
Hi @dabaoniu,

Can you please run the following to provide me with more information:

```bash
padloc --version; padloc --db-version; padloc --check-deps
```

Did you install PADLOC via `conda` or directly from GitHub? If via `conda` can you also run:

```bash
conda --version
```

Thanks!

**Comment by dabaoniu** [comment]
Hi @leightonpayne 

Thank you for the quick response!
This is the result after I ran the above command:

`padloc --version; padloc --db-version; padloc --check-deps`
padloc v1.1.0
padloc-db v2.0.0
[11:02:14] >> R installed (4.3.1)
[11:02:14] >> HMMER installed (3.3.2)
[11:02:14] >> Prodigal installed (2.6.3)
[11:02:15] >> R package 'tidyverse' installed (2.0.0)
[11:02:15] >> R package 'yaml' installed (2.3.7)
[11:02:16] >> R package 'getopt' installed (1.20.4)

`conda --version`
conda 23.9.0

Cheers!

**Comment by leightonpayne** [comment]
Thanks!

Due to an update to the format of our defence system models, PADLOC-DB v2.0.0 is only compatible with PADLOC v2.0.0 (whereas your installation is v1.1.0),

I'd recommend installing PADLOC v2.0.0 from scratch:

```bash
# Remove your old PADLOC env (if applicable)
conda env remove -n padloc
# Install PADLOC v2.0.0
conda create -n padloc -c conda-forge -c bioconda -c padlocbio padloc=2.0.0
```

**Comment by dabaoniu** [comment]
The problem was solved. Thank you so much for your help!
