### ISSUE TITLE
 database 

### ISSUE THREAD

**Issue by NK181092** [padlocbio/padloc#38]
I am following the steps to download PADLOC, the first two steps are working. As soon as I reach padloc--db-update, it is giving error that no such files is present 

check the path, and indeed the database file is missing

**Comment by leightonpayne** [comment]
Hi @NK181092,

Can you please post the exact code you are trying to run, and the resulting error message?

**Comment by NK181092** [comment]
Following the steps as mentionned to install the package.
As soon as it comes to update database, I am getting this error.

Unpacking database...
tar (child): /home/jp/miniconda3/envs/padloc/data/data.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now

I tried to install the database manually by putting it in the above mentionned path and when I am testing the software, it is giving me error of not being able to access the hmm files.

**Comment by leightonpayne** [comment]
I have a feeling this may be an issue with your `curl` installation? The `tar` error suggests that the compressed database has not being downloaded correctly.

Could you please try to run the following, and post the output:

```bash
DBREPO="https://github.com/padlocbio/padloc-db"
DATA="/home/jp/miniconda3/envs/padloc/data/"
VERSION="v2.0.0"

# Download compressed PADLOC data
echo ">> Running curl"
curl --version
curl -sL "${DBREPO}/archive/refs/tags/${VERSION}.tar.gz" --output ${DATA}/data.tar.gz

# Uncompress PADLOC data
echo ">> Running tar"
tar --version
tar -xzf ${DATA}/data.tar.gz --directory ${DATA} --strip-components 1 && rm ${DATA}/data.tar.gz
```

**Comment by NK181092** [comment]
Thank You, Issue resolved
