### ISSUE TITLE
Crispr error when running padloc

### ISSUE THREAD

**Issue by NK181092** [padlocbio/padloc#39]
When i am running Crispr output in padloc, i am getting the following error

Error in `mutate()`:
ℹ In argument: `domain.iE.value = as.numeric(Array_quality_score)`.
ℹ In group 1: `array.id = "CRISPR001"`.
Caused by error:
! object 'Array_quality_score' not found
Backtrace:
     ▆
  1. ├─global process_crisprdetect_gff(CRISPR_PATH, gff)
  2. │ └─... %>% ...
  3. ├─dplyr::mutate(...)
  4. ├─dplyr::arrange(., seqid, start)
  5. ├─dplyr::group_by(., seqid)
  6. ├─dplyr::mutate(., seqid = str_remove_all(seqid, "-.*"))
  7. ├─dplyr::mutate(...)
  8. ├─dplyr:::mutate.data.frame(...)
  9. │ └─dplyr:::mutate_cols(.data, dplyr_quosures(...), by)
 10. │   ├─base::withCallingHandlers(...)
 11. │   └─dplyr:::mutate_col(dots[[i]], data, mask, new_columns)
 12. │     └─mask$eval_all_mutate(quo)
 13. │       └─dplyr (local) eval()
 14. └─base::.handleSimpleError(...)
 15.   └─dplyr (local) h(simpleError(msg, call))
 16.     └─rlang::abort(message, class = error_class, parent = parent, call = error_call)
Execution halted
[18:22:30] ERROR >> errexit on line 425

**Comment by leightonpayne** [comment]
Hi @NK181092!

Could you please provide more information about the command you are running? (e.g. what options are you using? `--faa`, `--gff`, `--fna`, `--crispr`, etc.)

And, if possible, attach your input files here or [email them to me](mailto:leighton.payne@otago.ac.nz) so I can take a closer look at what might be going wrong,

Cheers!

**Comment by NK181092** [comment]
--fna and -crispr together 

trying to run padloc on fna and crisprdetect output together

**Comment by leightonpayne** [comment]
Hi @nk181092, thanks for sending through your files! This should be an easy fix,

If you're using the `--crispr` option, you need to run our patched version of CRISPRDetect (which generates a slightly differently formatted output to the vanilla CRISPRDetect package), then pass the output to PADLOC.

To install and run our patched version of CRISPRDetect, you can read the full details [here](https://github.com/padlocbio/padloc/blob/master/etc/README.md), but in short you need to:

```bash
# Install PADLOC via conda (if you haven't already)
conda create -n padloc -c conda-forge -c bioconda -c padlocbio padloc=2.0.0
```
```bash
# Activate the environment
conda activate padloc
```
```bash
# Download the latest database
padloc --db-update
```
```bash
# Run the CRISPRDetect install helper (packaged with PADLOC)
install-crisprdetect
```
```bash
# Run the CRISPRDetect helper (packaged with PADLOC)
run-crisprdetect --input your_genome.fna --output your_genome_crispr
```
```bash
# Run PADLOC (passing the generated `_crispr.gff`)
padloc --fna your_genome.fna --crispr your_genome_crispr.gff
```
