### ISSUE TITLE
Parsing errors 

### ISSUE THREAD

**Issue by raw937** [padlocbio/padloc#43]
Warning messages:
1: package ‘ggplot2’ was built under R version 4.3.3 
2: package ‘tidyr’ was built under R version 4.3.2 
3: package ‘readr’ was built under R version 4.3.2 
4: package ‘dplyr’ was built under R version 4.3.2 
5: package ‘stringr’ was built under R version 4.3.2 
Warning message:
One or more parsing issues, call `problems()` on your data frame for details, e.g.:
  dat <- vroom(...)
  problems(dat) 

Thoughts?

**Comment by leightonpayne** [comment]
I suspect this is related to #42, so closing in favour of continuing the conversation there.
