### ISSUE TITLE
ERROR: Internal Server Error

### ISSUE THREAD

**Issue by kelseydefaoite** [padlocbio/padloc#45]
When I've tried to submit a genome, I keep getting the error: ERROR: Internal Server Error.

**Comment by PlatypusBio** [comment]
Hi,

We think this was due to a resource limitation on the server. Hopefully now resolved.

Thanks for letting us know.

**Comment by JacksonLab** [comment]
Hi,

We think this was due to a resource limitation on the server. Should be resolved now.

Thanks for letting us know.
