### ISSUE TITLE
E-value full sequence or iEvalue domain

### ISSUE THREAD

**Issue by jpjarnoux** [padlocbio/padloc#46]
Hi! 

I would suggest improving the documentation on which value is used to filter on e-value. In the paper or the README, it seems to me you were using the full sequence e-value, but in the code, you are filtering on the domain e-value: https://github.com/padlocbio/padloc/blob/820306bc0ebfe1c225f318ce0c2da9969a606d22/bin/padloc.R#L590

I can understand the choice, but it should be explicitly written to understand why a HMM is assigned or not.

**Comment by leightonpayne** [comment]
Hi Jérôme, thanks for pointing this out, I'll make a note to update the documentation
