### ISSUE TITLE
Web server not working

### ISSUE THREAD

**Issue by jkdlvgsbdh** [padlocbio/padloc#49]
Hello, sorry for the inconvenience, but the PADLOC web server suddenly stopped loading. Is there any way that can be solved?
The message on the page is as follows:

This site can’t be reached
padloc.otago.ac.nz took too long to respond.

Thank you :)

**Comment by jkdlvgsbdh** [comment]
No worries, it just started working again! thank you :) have a lovely weekend :)

**Comment by JacksonLab** [comment]
Hi,

Thanks for the heads-up, I just restarted the server (haven't diagnosed why it when down, so hopefully stays up).

Cheers,

Simon
