### ISSUE TITLE
-p meta option is missing

### ISSUE THREAD

**Issue by genomesandMGEs** [padlocbio/padloc#7]
Hi,

Thanks for developing padloc, it looks cool! I was running this tool on several mobile elements, which tend to be quite smaller than chromosomes, and I got this error:

Error:  Sequence must be 20000 characters (only 5237 read).
(Consider running with the -p meta option or finding more contigs from the same genome.)

ERROR:   prodigal failed\n

Warning:  ideally Prodigal should be given at least 100000 bases for training.
You may get better results with the -p meta option.

However, the -p meta option is not available in the command line. Could you please fix this?

Thank you.

**Comment by leightonpayne** [comment]
Thanks for trying out PADLOC. According to [Prodigal's own documentation](https://github.com/hyattpd/prodigal/wiki/Advice-by-Input-Type#plasmids-phages-viruses-and-other-short-sequences), it's not recommended for use on sequences < 100 kbp. To fix this error, we've added a check for sequence length that will reject sequences < 100 kbp. 

If you still want to use Prodigal, then you can run it before using PADLOC with the `-p meta` / `-p anon` option, or use some other gene prediction software before using PADLOC.
